version: 2.1

jobs:
  test-with-emulators:
    docker:
      - image: circleci/openjdk:latest-node
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Setup functions
          command: |
            npm --prefix functions ci
            npm --prefix functions run build
      - run: npm ci
      - run:
          name: Test
          command: npm run test:ci
      - store_test_results:
          path: ./junit

workflows:
  version: 2
  firebase-test:
    jobs:
      - test-with-emulators
